name: client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  animated_splash_screen: ^1.3.0
  bloc: ^7.2.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.0
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  fluttertoast: ^8.2.8
  freezed_annotation: ^2.0.0
  go_router: ^14.6.0
  json_annotation: ^4.8.0
  lottie: ^3.1.3
  flutter_swipe_button: ^2.1.3
  http: ^1.2.2
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2

dev_dependencies:
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/loading.json
    - assets/images/dodge_signin.png
    - assets/images/customized_arrow.png
    - assets/images/google_icon.png
    - assets/images/image.png
    - assets/images/WELCOME_PAGE.png
    - assets/images/honda.png
    - assets/images/civic.png
    - assets/images/vios.png
    - assets/images/sorento.png

  fonts:
    - family: goodtimes
      fonts:
        - asset: assets/fonts/good-times-Regular.otf

    - family: nasalization
      fonts:
        - asset: assets/fonts/nasalization-rg.otf

    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/icon.png"
